# Veri Bilimi Eğitimi

## Veri Setini Tanıma

Amaç:
  1. Veri setinin genel yapısını tanımak ve temel özelliklerini incelemek
  2. Veri analizi öncesi gerekli ilk kontrolleri uygulamak

Adımlar:
  1. Veri setini yükle
  2. Veri setinin ilk ve son satırlarını incele
  3. Veri setinin boyutunu ve sütunlarını kontrol etmek
  4. Veri setinin genel bilgisini incele
  5. Özet istatistikleri görüntüle
  6. Veri tiplerini kontrol et
  7. Sayısal ve kategorik sütunları ayırmak
  8. Benzersiz (unique) değer sayılarını incelemek

In [ ]:
import pandas as pd

In [ ]:
# 1. Veri setini yükleme
df = pd.read_csv("e_ticaret_veri_seti.csv")

In [ ]:
# 2. Veri setinin ilk satırlarını inceliyoruz
df.head()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,49.9,Kredi Kartı,Yeni,3.0,5.0,Hayır,0.220,443.68
1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,0.10,29.9,Banka Kartı,VIP,4.0,1.0,Hayır,0.361,2685.17
2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,29.9,Kredi Kartı,Mevcut,6.0,2.0,Hayır,0.348,304.47
3,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,49.9,Kapıda Ödeme,Yeni,3.0,5.0,Hayır,0.250,1023.80
4,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,39.9,Dijital Cüzdan,Mevcut,4.0,5.0,Hayır,0.280,2439.03

In [ ]:
# 2. Veri setinin son satırlarını inceliyoruz
df.tail()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
1423,SIP101093,MUS1187,2024-06-08 20:42:00,İstanbul,Marmara,Spor,Yoga Matı,1,772.23,0.00,29.9,Kredi Kartı,Mevcut,3.0,2.0,Hayır,0.275,802.13
1424,SIP101193,MUS1297,2025-11-06 08:17:00,Gaziantep,Güneydoğu Anadolu,Spor,Suluk,2,187.03,0.00,59.9,Kredi Kartı,Yeni,2.0,4.0,Evet,0.243,433.96
1425,SIP101210,MUS1122,2025-03-07 09:07:00,NaN,Marmara,Elektronik,Webcam,4,894.47,0.10,49.9,Kredi Kartı,Mevcut,3.0,5.0,Hayır,0.355,3269.99
1426,SIP101060,MUS1189,2025-04-19 21:52:00,Kocaeli,Marmara,Kitap,Veri Bilimi 101,2,248.55,0.05,59.9,banka karti,Yeni,4.0,3.0,Hayır,0.373,532.14
1427,SIP100642,MUS1289,2024-09-22 16:36:00,Ankara,İç Anadolu,Kozmetik,Güneş Kremi,1,424.84,0.20,0.0,Dijital Cüzdan,Yeni,2.0,4.0,Hayır,0.317,339.87

In [ ]:
# 3. Veri setinin boyutunu ve sütunlarını kontrol etme
veri_seti_boyut = df.shape
veri_seti_boyut

(1428, 18)

In [ ]:
# satırlarını kontrol etme
satir_sayisi = df.shape[0]
print(f"satır sayısı: {satir_sayisi}")

satır sayısı: 1428

In [ ]:
# sütunlarını kontrol etme
sutun_sayisi = df.shape[1]
print(f"sütun sayısı: {sutun_sayisi}")

sütun sayısı: 18

In [ ]:
# sütun isimleri
for i, sutun in enumerate(df.columns, start = 1): # enumerate döngüye sokulan elemanları saymak için kullanılan bir fonksiyondur.
  print(f"{i}. {sutun}") # start = 1 sayma işleminin 1'den başlaması için

1. siparis_id
2. musteri_id
3. siparis_tarihi
4. sehir
5. bolge
6. kategori
7. urun_adi
8. adet
9. birim_fiyat
10. indirim_orani
11. kargo_ucreti
12. odeme_turu
13. musteri_tipi
14. teslimat_gunu
15. musteri_puani
16. iade_durumu
17. kar_marji_orani
18. toplam_tutar

In [ ]:
# 4. Veri setinin genel bilgisini inceleme
df.info() # sütun isimlerini, veri tiplerini, kayıp, eksik verileri görebiliriz

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1428 entries, 0 to 1427
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   siparis_id       1428 non-null   object
 1   musteri_id       1428 non-null   object
 2   siparis_tarihi   1428 non-null   object
 3   sehir            1403 non-null   object
 4   bolge            1428 non-null   object
 5   kategori         1428 non-null   object
 6   urun_adi         1428 non-null   object
 7   adet             1428 non-null   int64
 8   birim_fiyat      1428 non-null   float64
 9   indirim_orani    1412 non-null   float64
 10  kargo_ucreti     1428 non-null   float64
 11  odeme_turu       1393 non-null   object
 12  musteri_tipi     1386 non-null   object
 13  teslimat_gunu    1400 non-null   float64
 14  musteri_puani    1372 non-null   float64
 15  iade_durumu      1428 non-null   object
 16  kar_marji_orani  1428 non-null   float64
 17  toplam_tutar     1428 non-null   float64
dtypes: float64(7), int64(1), object(10)
memory usage: 200.9+ KB

In [ ]:
# 5. Özet istatistikleri görüntüleme
df.describe() # sayısal sütunlar için temel istatistikleri yazdırır

,adet,birim_fiyat,indirim_orani,kargo_ucreti,teslimat_gunu,musteri_puani,kar_marji_orani,toplam_tutar
count,1428.000000,1428.000000,1412.000000,1428.000000,1400.000000,1372.000000,1428.000000,1428.000000
mean,2.136555,658.477654,0.052054,39.725140,3.370714,4.002187,0.302799,1370.590336
std,2.015770,1042.414639,0.060115,14.185017,1.825990,1.096707,0.069795,2961.689500
min,1.000000,93.110000,0.000000,0.000000,1.000000,0.000000,0.180000,89.680000
25%,1.000000,199.185000,0.000000,29.900000,2.000000,3.000000,0.244750,323.855000
50%,2.000000,287.120000,0.050000,39.900000,3.000000,4.000000,0.305000,669.135000
75%,3.000000,819.177500,0.100000,49.900000,4.000000,5.000000,0.362000,1390.950000
max,38.000000,18145.230000,0.200000,59.900000,31.000000,7.000000,0.420000,63870.200000

In [ ]:
# 6. Veri tiplerini kontrol etme
df.dtypes #  df.info() komutuna benzer şekilde sütunların hangi türde veriler içerdiğini gösterir

siparis_id          object
musteri_id          object
siparis_tarihi      object
sehir               object
bolge               object
kategori            object
urun_adi            object
adet                 int64
birim_fiyat        float64
indirim_orani      float64
kargo_ucreti       float64
odeme_turu          object
musteri_tipi        object
teslimat_gunu      float64
musteri_puani      float64
iade_durumu         object
kar_marji_orani    float64
toplam_tutar       float64
dtype: object

In [ ]:
# 7. Sayısal ve kategorik sütunların ayrılması
# sayısal: float64, int64
sayisal_sutunlar = df.select_dtypes(include=["int64", "float64"]).columns
sayisal_sutunlar

Index(['adet', 'birim_fiyat', 'indirim_orani', 'kargo_ucreti', 'teslimat_gunu',
       'musteri_puani', 'kar_marji_orani', 'toplam_tutar'],
      dtype='object')

In [ ]:
# kategorik: object
kategorik_sutunlar = df.select_dtypes(include=["object"]).columns
kategorik_sutunlar

Index(['siparis_id', 'musteri_id', 'siparis_tarihi', 'sehir', 'bolge',
       'kategori', 'urun_adi', 'odeme_turu', 'musteri_tipi', 'iade_durumu'],
      dtype='object')

In [ ]:
# 8. Benzersiz (unique) değer sayılarını incelemek
for sutun in df.columns:
  print(f"{sutun}: {df[sutun].nunique()}")

siparis_id: 1400
musteri_id: 422
siparis_tarihi: 1398
sehir: 19
bolge: 6
kategori: 15
urun_adi: 30
adet: 10
birim_fiyat: 1381
indirim_orani: 5
kargo_ucreti: 5
odeme_turu: 12
musteri_tipi: 7
teslimat_gunu: 11
musteri_puani: 8
iade_durumu: 2
kar_marji_orani: 241
toplam_tutar: 1397