# Veri Bilimi Eğitimi

## Kayıp Veri (Missing Value)
Amaç:
  1. Eksik veri tespiti ve farklı eksik veri çözüm yöntemlerini uygulamak
  2. Eğitimde kullanılacak güncel veri setini kaydetme

Adımlar:
  1. Veri setini yükleme
  2. Eksik verileri tespit etme
  3. Eksik veri oranlarını hesaplama
  4. Eksik veri içeren satırları incele
  5. Eksik verileri silmek
  6. Sayısal eksik verileri ortalama ile doldur
  7. Sayısal eksik verileri medyan ile doldur
  8. Sayısal eksik verileri mod ile doldur
  9. Kategorik eksik verileri mod ile doldur
  10. Kategorik eksik verileri sabit bir değer ile doldurmak
  11. Eğitimde kullanılacak olan güncel veri setini oluştur
  12. Düzenlenmiş veri setini kaydet

In [ ]:
import pandas as pd

In [ ]:
# 1. veri setini yükle
df = pd.read_csv("e_ticaret_veri_seti.csv")

In [ ]:
# 2. eksik verileri tespit etme
df.isnull().sum()

siparis_id          0
musteri_id          0
siparis_tarihi      0
sehir              25
bolge               0
kategori            0
urun_adi            0
adet                0
birim_fiyat         0
indirim_orani      16
kargo_ucreti        0
odeme_turu         35
musteri_tipi       42
teslimat_gunu      28
musteri_puani      56
iade_durumu         0
kar_marji_orani     0
toplam_tutar        0
dtype: int64

In [ ]:
# 3. eksik veri oranlarını hesapla
eksik_sayilari = df.isnull().sum()
eksik_oranlari = 100 * (eksik_sayilari / len(df))
eksik_oranlari

siparis_id         0.000000
musteri_id         0.000000
siparis_tarihi     0.000000
sehir              1.750700
bolge              0.000000
kategori           0.000000
urun_adi           0.000000
adet               0.000000
birim_fiyat        0.000000
indirim_orani      1.120448
kargo_ucreti       0.000000
odeme_turu         2.450980
musteri_tipi       2.941176
teslimat_gunu      1.960784
musteri_puani      3.921569
iade_durumu        0.000000
kar_marji_orani    0.000000
toplam_tutar       0.000000
dtype: float64

In [ ]:
# 4. eksik veri içeren satırları incele
eksik_veri_olan_satirlar = df[df.isnull().any(axis = 1)]
# df[ ... ]: Köşeli parantez, DataFrame'de filtreleme yapar.
# any(): "İçinde herhangi bir tane bile boş var mı?" diye sorar.

eksik_veri_olan_satirlar.head(10)

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
19,SIP100677,MUS1148,2024-07-11 16:24:00,Adana,Akdeniz,Spor,Dambıl Seti,4,1517.65,0.0,29.9,Kapıda Ödeme,Mevcut,3.0,NaN,Hayır,0.311,6100.50
33,SIP101126,MUS1406,2024-09-11 20:05:00,Mersin,Akdeniz,Elektronik,Bluetooth Hoparlör,1,1159.89,0.1,39.9,Kredi Kartı,NaN,2.0,4.0,Hayır,0.204,1083.80
50,SIP101040,MUS1386,2025-04-01 09:30:00,Trabzon,Karadeniz,Spor,Dambıl Seti,1,1554.15,0.0,49.9,Banka Kartı,NaN,4.0,5.0,Hayır,0.217,1604.05
60,SIP100890,MUS1271,2024-11-07 19:47:00,İzmir,Ege,Kitap,Girişimcilik,4,216.38,NaN,49.9,Kredi Kartı,Yeni,1.0,3.0,Hayır,0.199,915.42
61,SIP101317,MUS1060,2024-09-05 20:49:00,NaN,Akdeniz,Ev ve Yaşam,Saklama Kutusu,1,233.63,0.1,29.9,Dijital Cüzdan,Yeni,5.0,2.0,Hayır,0.385,240.17
70,SIP100715,MUS1033,2024-11-10 21:50:00,İstanbul,Marmara,Ev ve Yaşam,Termos,1,552.05,0.0,39.9,NaN,Mevcut,2.0,3.0,Hayır,0.185,591.95
82,SIP100807,MUS1431,2025-01-07 14:12:00,Ankara,İç Anadolu,Kozmetik,Güneş Kremi,1,451.28,0.0,49.9,Kredi Kartı,NaN,4.0,5.0,Hayır,0.315,501.18
84,SIP100679,MUS1310,2024-05-20 18:51:00,İzmir,Ege,Ev ve Yaşam,Termos,2,477.62,0.0,49.9,Kredi Kartı,Mevcut,NaN,4.0,Hayır,0.323,1005.14
86,SIP101071,MUS1131,2024-09-18 12:24:00,NaN,İç Anadolu,Elektronik,Powerbank,1,816.74,0.0,39.9,Banka Kartı,Yeni,3.0,5.0,Hayır,0.301,856.64
92,SIP101366,MUS1347,2025-03-04 14:00:00,Bursa,Marmara,Ev ve Yaşam,Organizer,1,272.40,0.0,29.9,Kredi Kartı,Mevcut,1.0,NaN,Hayır,0.212,302.30

In [ ]:
# 5. Eksik verileri silme
df_silinen = df.dropna() # dropna ile eksik değer içeren satırları veri setinden çıkarttık

In [ ]:
df_silinen.shape

(1239, 18)

In [ ]:
# 6. Sayısal eksik verilerin ortalama ile doldurulması
df_ortalama = df.copy()
sayisal_sutunlar = df_ortalama.select_dtypes(include = ["int64", "float64"]).columns
sayisal_sutunlar

Index(['adet', 'birim_fiyat', 'indirim_orani', 'kargo_ucreti', 'teslimat_gunu',
       'musteri_puani', 'kar_marji_orani', 'toplam_tutar'],
      dtype='object')

In [ ]:
for sutun in sayisal_sutunlar:
  df_ortalama[sutun] = df_ortalama[sutun].fillna(df_ortalama[sutun].mean())      #fillna boşlukları doldurmak için

In [ ]:
df_ortalama[sayisal_sutunlar].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [ ]:
# 7. sayısal eksik verileri medyan ile doldurma
df_medyan = df.copy()
for sutun in sayisal_sutunlar:
  df_medyan[sutun] = df_medyan[sutun].fillna(df_medyan[sutun].median())
df_medyan[sayisal_sutunlar].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [ ]:
# 8. Sayısal eksik verileri mod ile doldurma
df_mod = df.copy()
for sutun in sayisal_sutunlar:
  mod_degeri = df_mod[sutun].mode()[0] # bu fonksiyon seri döndürür 0. indeksi alrak modu buluyoruz
  df_mod[sutun] = df_mod[sutun].fillna(mod_degeri)
df_mod[sayisal_sutunlar].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [ ]:
# 9. kategorik eksik verileri mod ile doldurma
df_mod_kategorik = df.copy()
kategorik_sutunlar = df_mod_kategorik.select_dtypes(include = ["object"]).columns
kategorik_sutunlar

Index(['siparis_id', 'musteri_id', 'siparis_tarihi', 'sehir', 'bolge',
       'kategori', 'urun_adi', 'odeme_turu', 'musteri_tipi', 'iade_durumu'],
      dtype='object')

In [ ]:
for sutun in kategorik_sutunlar:
  mod_degeri = df_mod_kategorik[sutun].mode()[0]
  df_mod_kategorik[sutun] = df_mod_kategorik[sutun].fillna(mod_degeri)

In [ ]:
df_mod_kategorik[kategorik_sutunlar].isnull().sum()

siparis_id        0
musteri_id        0
siparis_tarihi    0
sehir             0
bolge             0
kategori          0
urun_adi          0
odeme_turu        0
musteri_tipi      0
iade_durumu       0
dtype: int64

In [ ]:
# 10. kategorik eksik verileri sabit bir değer ile dolduralım
df_sabit_kategorik = df.copy()

for sutun in kategorik_sutunlar:
  df_sabit_kategorik[sutun] = df_sabit_kategorik[sutun].fillna("Bilinmiyor")

In [ ]:
df_sabit_kategorik[kategorik_sutunlar].isnull().sum()

siparis_id        0
musteri_id        0
siparis_tarihi    0
sehir             0
bolge             0
kategori          0
urun_adi          0
odeme_turu        0
musteri_tipi      0
iade_durumu       0
dtype: int64

In [ ]:
# 11. eğitim kullanacağımız güncel veri seti
# - sayısal eksik verileri medyan ile doldur
# - kategorik eksik verileri mod ile doldur

In [ ]:
df_guncel = df.copy()

In [ ]:
for sutun in sayisal_sutunlar:
  df_guncel[sutun] = df_guncel[sutun].fillna(df_guncel[sutun].median())

In [ ]:
for sutun in kategorik_sutunlar:
  mod_degeri = df_guncel[sutun].mode()[0]
  df_guncel[sutun] = df_guncel[sutun].fillna(mod_degeri)

In [ ]:
df_guncel.isnull().sum()

siparis_id         0
musteri_id         0
siparis_tarihi     0
sehir              0
bolge              0
kategori           0
urun_adi           0
adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
odeme_turu         0
musteri_tipi       0
teslimat_gunu      0
musteri_puani      0
iade_durumu        0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [ ]:
# 12. düzenlenmiş veri setini kaydedelim
kayit_dosyasi = "e_ticaret_veri_seti_eksik_veriler_duzenlendi.csv"
df_guncel.to_csv(kayit_dosyasi, index = False)