# Veri Bilimi Eğitimi

## Tekrarlayan ve Tutarsız Kayıtlar
Amaç:
  1. Veri setindeki tekrarlayan ve tutarsız kayıtları tespit edip temizlemek
  2. Eğitimde kullanılacak güncel veri setini kaydet

Adımlar:
  1. Veri setini yüklemek
  2. Tekrarlayan kayıtları tespit etmek
  3. Tekrarlayan kayıtları incelemek
  4. Tekrarlayan kayıtları temizlemek
  5. Tutarsız kategorik değerleri incelemek
  6. Şehir sütunundaki tutarsız değerleri düzeltmek
  7. Kategori sütunundaki tutarsız değerleri düzeltmek
  8. Ödeme türü sütunundaki tutarsız değerleri düzeltmek
  9. Müşteri tipi sütunundaki tutarsız değerleri düzeltmek
  10. Mantıksal olarak hatalı kayıtları incele
  11. Mantıksal olarak hatalı kayıtları temizleme
  12. Güncellenmiş veri setini kaydet

In [ ]:
import pandas as pd

In [ ]:
# 1. Veri setini yükleme
df = pd.read_csv("e_ticaret_veri_seti_veri_tipleri_duzenlendi.csv")
df.shape

(1428, 22)

In [ ]:
# 2. tekrarlayan kayıtları tespit et
tekrarlayan_kayitlar = df[df.duplicated()]
len(tekrarlayan_kayitlar)

28

In [ ]:
# 3. tekrarlayan kayıtları incele
tekrarlayan_kayitlar.head(5)

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,...,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu,haftanin_gunu
174,SIP100479,MUS1099,2025-06-10 20:32:00,İstanbul,Marmara,Kozmetik,Güneş Kremi,3,455.19,0.00,...,Yeni,1.0,5.0,Hayır,0.200,1415.47,2025,6,10,Tuesday
315,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,...,Mevcut,4.0,5.0,Hayır,0.280,2439.03,2024,8,19,Monday
324,SIP100533,MUS1128,2024-11-19 14:22:00,Trabzon,Karadeniz,Kitap,Python Notları,2,225.82,0.00,...,Yeni,4.0,5.0,Hayır,0.234,491.54,2024,11,19,Tuesday
613,SIP100725,MUS1146,2025-05-24 10:10:00,Kocaeli,Marmara,Kitap,Zaman Yönetimi,2,154.18,0.05,...,Yeni,3.0,5.0,Hayır,0.385,342.84,2025,5,24,Saturday
637,SIP100940,MUS1032,2025-03-25 20:06:00,Samsun,Karadeniz,Kozmetik,Serum,1,507.46,0.15,...,Mevcut,3.0,4.0,Evet,0.402,471.24,2025,3,25,Tuesday

In [ ]:
# 4. tekrarlayan kayıtları temizle
df = df.drop_duplicates()
df.shape

(1400, 22)

In [ ]:
# 5. tutarsız değerlerin incelenmesi
df["sehir"].unique()
# 'istanbul', 'ankara', 'Istanbul', 'gaziantep', 'Izmir

array(['İstanbul', 'Gaziantep', 'Kayseri', 'Antalya', 'Konya', 'Ankara',
       'Bursa', 'Trabzon', 'Adana', 'Mersin', 'Kocaeli', 'İzmir',
       'Eskişehir', 'Samsun', 'istanbul', 'ankara', 'Istanbul',
       'gaziantep', 'Izmir'], dtype=object)

In [ ]:
df["kategori"].unique()
# 'Ofis', 'ofis', 'Elektronik ',  'Elektronik', 'spor', 'kozmetık', 'ev ve yaşam', 'kitap', 'Kozmetik ', 'elektronik', 'Ev&Yaşam'

array(['Kozmetik', 'Spor', 'Kitap', 'Elektronik', 'Ofis', 'ofis',
       'Ev ve Yaşam', 'Elektronik ', 'spor', 'kozmetık', 'ev ve yaşam',
       'kitap', 'Kozmetik ', 'elektronik', 'Ev&Yaşam'], dtype=object)

In [ ]:
df["odeme_turu"].unique()

array(['Kredi Kartı', 'Banka Kartı', 'Kapıda Ödeme', 'Dijital Cüzdan',
       'Havale/EFT', 'Kart', 'kredi kartı', 'dijital cüzdan', 'eft',
       'banka karti', 'Kapida Odeme', 'Havale'], dtype=object)

In [ ]:
df["musteri_tipi"].unique()

array(['Yeni', 'VIP', 'Mevcut', 'yeni', 'Vip', 'mevcut', 'vip'],
      dtype=object)

In [ ]:
# yardımcı fonksiyon: metinleri normalize edelim
# büyük küçük harf dönüşümleri, boşlukların kaldırılması, Türkçe karakter kaynaklı farkların düzenlenmesi
def metin_normalize_et(series):

  return(
      series.astype(str)
      .str.strip()
      .str.lower()
      .str.replace("i̇", "i", regex=False)
      .str.replace("ı", "i", regex=False)
      .str.replace("ö", "o", regex=False)
      .str.replace("ü", "u", regex=False)
      .str.replace("ç", "c", regex=False)
      .str.replace("ş", "s", regex=False)
      .str.replace("ğ", "g", regex=False)
  )

In [ ]:
# 6. şehir sütunundaki tutarsız değerleri düzeltme
df["sehir"] = metin_normalize_et(df["sehir"])
df["sehir"].unique()

array(['istanbul', 'gaziantep', 'kayseri', 'antalya', 'konya', 'ankara',
       'bursa', 'trabzon', 'adana', 'mersin', 'kocaeli', 'izmir',
       'eskisehir', 'samsun'], dtype=object)

In [ ]:
sehir_duzeltme_haritasi = {
    "istanbul": "İstanbul",
    "ankara": "Ankara",
    "izmir": "İzmir",
    "antalya": "Antalya",
    "konya": "Konya",
    "bursa": "Bursa",
    "adana": "Adana",
    "gaziantep": "Gaziantep",
    "mersin": "Mersin",
    "kayseri": "Kayseri",
    "eskisehir": "Eskişehir",
    "samsun": "Samsun",
    "trabzon": "Trabzon",
    "kocaeli": "Kocaeli"
}
df["sehir"] = df["sehir"].replace(sehir_duzeltme_haritasi)
df["sehir"].unique()

array(['İstanbul', 'Gaziantep', 'Kayseri', 'Antalya', 'Konya', 'Ankara',
       'Bursa', 'Trabzon', 'Adana', 'Mersin', 'Kocaeli', 'İzmir',
       'Eskişehir', 'Samsun'], dtype=object)

In [ ]:
# 7. kategori sütunundaki tutarsız değerleri düzeltme
df["kategori"] = metin_normalize_et(df["kategori"])
df["kategori"].unique()

array(['kozmetik', 'spor', 'kitap', 'elektronik', 'ofis', 'ev ve yasam',
       'ev&yasam'], dtype=object)

In [ ]:
kategori_duzeltme_haritasi = {
    "elektronik": "Elektronik",
    "kitap": "Kitap",
    "kozmetik": "Kozmetik",
    "kozmetık": "Kozmetik",
    "spor": "Spor",
    "ev yasam": "Ev Yaşam",
    "ev ve yasam": "Ev Yaşam",
    "ev&yasam": "Ev Yaşam",
    "ofis": "Ofis"
}
df["kategori"] = df["kategori"].replace(kategori_duzeltme_haritasi)
df["kategori"].unique()

array(['Kozmetik', 'Spor', 'Kitap', 'Elektronik', 'Ofis', 'Ev Yaşam'],
      dtype=object)

In [ ]:
# 8. ödeme türü sütunundaki tutarsız değerleri düzeltelim
df["odeme_turu"] = metin_normalize_et(df["odeme_turu"])
df["odeme_turu"].unique()

array(['kredi karti', 'banka karti', 'kapida odeme', 'dijital cuzdan',
       'havale/eft', 'kart', 'eft', 'havale'], dtype=object)

In [ ]:
odeme_turu_duzeltme_haritasi = {
    "kredi karti": "Kredi Kartı",
    "kart": "Kredi Kartı",
    "banka karti": "Banka Kartı",
    "dijital cuzdan": "Dijital Cüzdan",
    "kapida odeme": "Kapıda Ödeme",
    "havale": "Havale/EFT",
    "eft": "Havale/EFT",
    "havale/eft": "Havale/EFT"
}
df["odeme_turu"] = df["odeme_turu"].replace(odeme_turu_duzeltme_haritasi)
df["odeme_turu"].unique()

array(['Kredi Kartı', 'Banka Kartı', 'Kapıda Ödeme', 'Dijital Cüzdan',
       'Havale/EFT'], dtype=object)

In [ ]:
# 9. müşteri tipi sütunundaki tutarsız değerleri düzeltelim
df["musteri_tipi"] = metin_normalize_et(df["musteri_tipi"])
df["musteri_tipi"].unique()

array(['yeni', 'vip', 'mevcut'], dtype=object)

In [ ]:
musteri_tipi_duzeltme_haritasi = {
    "mevcut": "Mevcut",
    "yeni": "Yeni",
    "vip": "VIP"
}
df["musteri_tipi"] = df["musteri_tipi"].replace(musteri_tipi_duzeltme_haritasi)
df["musteri_tipi"].unique()

array(['Yeni', 'VIP', 'Mevcut'], dtype=object)

In [ ]:
df["musteri_tipi"].value_counts()

musteri_tipi
Mevcut    716
Yeni      520
VIP       164
Name: count, dtype: int64

In [ ]:
# 10. mantıksal olarak hatalı kayıtları inceleme
# negatif yada anlamsız değerler bazı kayıtlarda veri kalitesini düşürebilir
hatali_kayitlar = df[
    (df["adet"] <= 0) |
    (df["toplam_tutar"] <= 0) |
    (df["birim_fiyat"] <= 0) |
    (df["teslimat_gunu"] < 0) |
    (df["musteri_puani"] < 0) |
    (df["musteri_puani"] > 5) |
    (df["kargo_ucreti"] < 0)
]
len(hatali_kayitlar)

2

In [ ]:
pd.set_option("display.max_columns", None)
hatali_kayitlar

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu,haftanin_gunu
609,SIP100095,MUS1165,2025-10-12 21:31:00,İstanbul,Marmara,Kozmetik,Şampuan,2,190.17,0.10,0.0,Dijital Cüzdan,Mevcut,3.0,6.0,Hayır,0.416,342.31,2025,10,12,Sunday
1008,SIP101290,MUS1225,2024-01-16 21:46:00,Kocaeli,Marmara,Kozmetik,Yüz Temizleme Jeli,2,303.82,0.05,29.9,Kredi Kartı,Yeni,5.0,7.0,Evet,0.287,607.16,2024,1,16,Tuesday

In [ ]:
# 11. mantıksal hataları temizleyelim
df = df[
    (df["adet"] > 0) &
    (df["toplam_tutar"] > 0) &
    (df["birim_fiyat"] > 0) &
    (df["teslimat_gunu"] >= 0) &
    (df["musteri_puani"] >= 0) &
    (df["musteri_puani"] <= 5)
]
df.shape

(1398, 22)

In [ ]:
# 12. güncellenmiş verinini kaydedilmesi
df.to_csv("e_ticaret_veri_seti_tekrarlayan_kayitlar_duzenlendi.csv")