# Veri Bilimi Eğitimi

## Pivot Tablo Analizi

Amaç:
  1. Veri setini iki yönli kırılımlar ile özetleyerek pivot tablo mantığını kavramak
  2. Pivot tablo ile karşılaştırmalı analizler ve sonuçların yorumlanması

Adımlar:
  1. veri setini yükle
  2. Kategori ve müşteri tipine göre pivot tablo analizi
  3. Şehir ve ödeme türüne göre pivot tablo analizi
  4. Kategori ve ödeme türüne göre pivot tablo analizi
  5. Şehir ve müşteri tipine göre pivot tablo analizi

In [ ]:
import pandas as pd

In [ ]:
# 1. veri setini yükle
df = pd.read_csv("e_ticaret_veri_seti_aykiri_degerler_duzenlendi.csv")
df.head()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,...,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu,haftanin_gunu
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,...,Yeni,3.0,5.0,Hayır,0.220,443.68,2024,1,13,Saturday
1,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,...,Yeni,3.0,5.0,Hayır,0.250,1023.80,2024,8,10,Saturday
2,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,...,Mevcut,4.0,5.0,Hayır,0.280,2439.03,2024,8,19,Monday
3,SIP100687,MUS1147,2025-08-09 08:42:00,Konya,İç Anadolu,Kozmetik,Nemlendirici,2,417.02,0.00,...,Mevcut,4.0,5.0,Hayır,0.220,893.94,2025,8,9,Saturday
4,SIP100254,MUS1447,2024-07-30 09:06:00,Konya,İç Anadolu,Elektronik,Bluetooth Hoparlör,1,1327.75,0.05,...,Mevcut,4.0,5.0,Hayır,0.283,1291.26,2024,7,30,Tuesday

In [ ]:
# 2. kategori ve müşteri tipine göre pivot tablo analizi
# her kategori için müşteri tiplerine göre ortalama toplam tutar
pivot_kategori_musteri = pd.pivot_table(
    df,
    index = "kategori",
    columns = "musteri_tipi",
    values = "toplam_tutar",
    aggfunc = "mean"
).round(1)
pivot_kategori_musteri

musteri_tipi  Mevcut     VIP    Yeni
kategori
Elektronik    1592.5  1392.6  1451.1
Ev Yaşam       798.0   837.7   716.6
Kitap          481.4   577.9   530.4
Kozmetik       720.0   725.9   775.9
Ofis           276.4   252.7   310.7
Spor          1002.5  1264.1   981.1

In [ ]:
# 3. şehir ve ödeme türü göre pivot tablo analizi
# her kategori için müşteri tiplerine göre ortalama toplam tutar
pivot_sehir_odeme_turu = pd.pivot_table(
    df,
    index = "sehir",
    columns = "odeme_turu",
    values = "toplam_tutar",
    aggfunc = "sum"
).round(1)
pivot_sehir_odeme_turu

odeme_turu  Banka Kartı  Dijital Cüzdan  Havale/EFT  Kapıda Ödeme  Kredi Kartı
sehir
Adana            9186.0          9134.0      5565.5        2466.4      24001.3
Ankara          13764.1         13798.7     12892.8        7329.5      48936.1
Antalya         10871.3          7115.7      6658.0        5511.6      33556.2
Bursa            3694.8          8030.9      5853.7        6095.0      23108.3
Eskişehir        4313.3          8010.6       707.9        3395.3      21122.9
Gaziantep        4930.2          7119.0      3746.8        1395.0      18049.3
Kayseri          2957.4          2655.7      6466.2        3307.6       9491.8
Kocaeli          1579.2          5792.3      2891.3        2839.0       8191.2
Konya           15601.8          9379.3      4163.0        2611.8      27668.4
Mersin           9461.5          4307.8      2454.0         153.2      21667.4
Samsun           5068.7          9928.5      3619.5         177.3      17469.5
Trabzon          6164.2          2179.8      4533.4           NaN      17517.8
İstanbul        45163.2         28373.6     24956.5        5937.2     119590.0
İzmir           10255.4         14085.4      8385.8        6894.2      49097.9

In [ ]:
# 4. kategori ve ödeme türüne göre pivot tablo analizi
pivot_kategori_odeme = pd.pivot_table(
    df,
    index = "kategori",
    columns =  "odeme_turu",
    values = "musteri_puani",
    aggfunc = "mean"
).round(2)
pivot_kategori_odeme

odeme_turu  Banka Kartı  Dijital Cüzdan  Havale/EFT  Kapıda Ödeme  Kredi Kartı
kategori
Elektronik         4.04            4.25        4.28          4.43         4.28
Ev Yaşam           4.16            4.23        4.00          4.21         4.36
Kitap              4.25            4.22        4.00          4.62         4.27
Kozmetik           4.48            4.33        4.36          4.53         4.41
Ofis               4.29            4.15        4.30          4.31         4.23
Spor               4.20            4.39        4.07          4.15         4.28

In [ ]:
# 5. şehir ve müşteri tipi göre pivot tablo analizi
pivot_sehir_musteri = pd.pivot_table(
    df,
    index = "sehir",
    columns =  "musteri_tipi",
    values = "kargo_ucreti",
    aggfunc = "mean"
).round(2)
pivot_sehir_musteri

musteri_tipi  Mevcut    VIP   Yeni
sehir
Adana          40.16  34.92  42.12
Ankara         41.82  37.06  39.91
Antalya        38.63  36.57  40.19
Bursa          38.62  39.90  40.23
Eskişehir      36.38  39.90  39.04
Gaziantep      38.66  45.61  41.58
Kayseri        43.37  45.90  41.90
Kocaeli        42.63  46.57  40.49
Konya          38.12  35.92  39.90
Mersin         40.68  39.90  41.02
Samsun         39.49  37.90  36.78
Trabzon        34.91  35.90  44.02
İstanbul       39.09  39.60  36.72
İzmir          42.21  38.42  37.52